### PR TITLE
nil contextTitle crash fixed[IOS] && getPlayerState error fixed[ANDROID]

### PR DESCRIPTION
**Pull request by srfaytkn**

### CODE REVIEW

**Comment by darek607** [comment]
Thank you guy! @cjam Please merge it and release new version. Without this iOS app is crashing when trying to pause / play or get player state with the error:

`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'`

**Comment by cjam** [comment]
Thanks for the PR @srfaytkn!

**Comment by cjam** [comment]
@darek607 done!  0.3.8 has been released with these fixes

**Comment by darek607** [comment]
Thank you very much!

**Pull request merged**
