### PR TITLE
Android Support

### PR DESCRIPTION
**Pull request by YozhikM**
WIP
I'll to implement yet "Auth" later
/dist need to use this variant without publishing in our project.

Thanks for your good job on iOS

### CODE REVIEW

**Comment by cjam** [comment]
Woah, awesome!  I'll take a look at this ASAP.

**Comment by cjam** [comment]
Sorry I've been so delayed on this, I've been swamped with other things on my plate.  I hope I'll have time to take a look at this on the weekend.

**Comment by jsj1027** [comment]
Hi so i've been looking to use this project for a cross platform app. For reasons we are doing android development first. 

My current issue is I can not get the android code in this PR to build.
ive made sure I have gradle and groovy set up,

When I attempt to build the project in android studio I get this error


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-events:generateDebugRFile'.
> Could not resolve all files for configuration ':react-native-events:debugCompileClasspath'.
   > Could not find com.android.support:recyclerview-v7:23.0.1.
     Required by:
         project :react-native-events > com.facebook.react:react-native:0.20.1
   > Could not find com.android.support:appcompat-v7:23.0.1.
     Required by:
         project :react-native-events > com.facebook.react:react-native:0.20.1
   > Could not find com.android.support:support-v4:21.0.3.
     Required by:
         project :react-native-events > com.facebook.fresco:imagepipeline:0.8.1
         project :react-native-events > com.facebook.fresco:drawee:0.8.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by jsj1027** [comment]
@YozhikM Any advice for me?

**Comment by YozhikM** [comment]
During this week, I’ll see what and how. Or the next, when I will have a vacation and free time.

**Comment by jsj1027** [comment]
Thank you!

**Comment by YozhikM** [comment]
Hey.
I apologize for my long absence.

I found a problem that is stopping you from running the code. You need to add mavenCentral() like this.

I cleaned the code so that nothing would interfere with the merge.

I want to share the good news. We have been using this code for more than a month in production.

In the future, I am ready to help with project documentation, because it lacks a clear description of the implementation action. There is also no clarification on what is not available in the mobile SDKs, for example, searching for or getting user playlists.

Also, I want to draw attention to two important changes that I propose for implementation.

First: replace the scope parameter with scopes, because periodically you need to request not one, but several. For example, not only streaming, but user-read-private to find out the type of user subscription. 

Second: rename initialize to login. The whole process of requesting access from a user looks exactly like authorization for him. Accordingly, it must be properly named. 

Thank you so much for the implementation for iOS. You saved me a lot of time!

**Comment by cjam** [comment]
Hey @YozhikM .  First of all, thanks for all of your work on the android side of things.  This is really great.  I spent a lot of time getting into the world of Objective C and was having a hard time getting myself to that same level on the android side.  I would love to try this branch out, does it work with the example project in the root?  I have spent my time on the iOS side of things and am not sure the best way to get up and running with the android side.  


I like your ideas about the docs, I kinda started a table in the root readme to show the portions of the API that are not available, but I think this can be improved and am open to your ideas.

As for your proposed changes I don't see any issues with changing `initialize` to `login`.  As for the `scope`->`scopes` I think I had kept it as `scope` since they are structured in bit flag enum in which each entry represents one scope that can be combined with any other scope to form the scopes of access necessary.  So from the standpoint of the API, the Scope was to represent the data type of a Spotify Auth Scope, but in general, they can / are used in combination.

**Comment by YozhikM** [comment]
How can enum be used in JS in the same way as in Objective-C?

On Android, they look like list of strings.

**Comment by cjam** [comment]
> How can enum be used in JS in the same way as in Objective-C?
> 
> On Android, scopes looks like a list of strings.

@YozhikM Ah I see, well that's inconvenient.  Perhaps a simple mapping between the scope flags and android scope strings would suffice.  I modeled it after the iOS SDK since I started there.  I do enjoy the developer experience of using flag enums for scopes, so perhaps just a simple wrapper around the initialize/authorize when used for android would suffice.

I'm still working on trying to get the example in the repo running on an android device I have, after I get it up and running I can have a look making some of the changes suggested.

**Comment by jsj1027** [comment]
@YozhikM Thank you for responding. 

I added the google repository to the react native events node module but sadly I can't get it to build. Currently the issue is that it can't find spotify-app-remote-release-0.7.0.

This is the full error message. 
https://pastebin.com/PBn04T2W

**Comment by MrBuggySan** [comment]
Do you have instructions on how to install this into a react-native project? (I'm a bit of a noobie here)As I see that this new android integration is not worked into the example/ app yet. 

I'd like to test it out. Thanks for your work @YozhikM

**Comment by cjam** [comment]
hey @YozhikM,

So I've pulled down your PR locally and have been working through getting the example application running.  I haven't spent a lot of time on android so it's taken me a while to work with all of the gradle files and get everything running.  But I do have things running.  There are a few things that will need to be unified between iOS and Android which I don't mind doing as I go through and test against the example app.

The first thing that comes up is the `login` / `initialize` change.  I feel like the most appropriate name for it would be `authenticate` since if you're logged into Spotify it will just kick you back once you've agreed and immediately on subsequent times.  I'll keep track of changes to produce some documentation around installing for android which will hopefully help @MrBuggySan and @jsj1027.  Once I get something more stable I'll figure out how to get it pushed into this existing PR.

**Comment by jsj1027** [comment]
@cjam Oh thank goodness you've been able to get it working at least for yourself. I've been messing with it locally for weeks and have gotten basically nowhere. Truth be told I have 0 android experience before this, so maybe its just been my lack of understanding what to do.

Thank you and I'm very much looking forward to the docs.

**Comment by cjam** [comment]
@jsj1027 yea truth be told I haven't done much android before this and had to go pretty deep into the weeds on the weekend.  @YozhikM I'm not sure the best way to update/collaborate on this PR since it's coming from your fork.  Any thoughts?

**Comment by jsj1027** [comment]
@cjam I think as the main project owner you may be able to be granted permissions to push commits to the branch.

**Comment by jsj1027** [comment]
@YozhikM @cjam can an android version of the example be added to the README.md?

**Comment by cjam** [comment]
@jsj1027 I will definitely add some docs with the results of what I've learned along the way of getting it up and running.  I think things are getting close.  I'm incorporating some of the suggestions that @YozhikM had around scopes. I've got the Auth side working and pretty close to parity with the iOS implementation.  I'm currently just having issues with the Connection side of things.  But a big thanks to @YozhikM for the hard work on the initial implementation.

I've forked his and am doing some work on that as that seems to be the path to updating the PR.  I just wish I had more time to work on it to get this PR done and be able to have support for android!

**Comment by cjam** [comment]
Good news.  I finally got the example app up and running on my old android device.  Now I can start going through the functionality and seeing what things work the same and what things need some tweaking to match iOS (as close as we can anyways)

**Comment by cjam** [comment]
Alright everyone.  I've been hard at work and have the android example at parity (minus the bits that aren't implemented in spotify's android sdk).  Things are looking good.  I haven't quite done up the Docs for the readme.  But I'm eager to get this integrated and publish a new version that can be used and tried.  Stay Tuned

**Comment by MrBuggySan** [comment]
Looking forward to use it !

**Comment by cjam** [comment]
I needed to be able to update this initial PR and make sure everything was working in the example application.  I have now done this and issued PR #43 for this which I'll be merging shortly.  Also, I've pushed out a pre-release that you can try `react-native-spotify-remote@next`.  I want to try and install it into my own app and update any docs before I move it over to latest.

**Pull request closed without merging**
