### PR TITLE
Bump Spotify Android SDK version and clean up android configs

### LINKED ISSUE #161: Does not work when targeting Android SDK v30 (React Native 0.65+)
I recently update my react-native version to v0.65 (which targets android sdk 30) and realize that `react-native-spotify-remote` stops working.

Instead of opening the Spotify app the authenticate, it opens a Sign in modal, but after filling in the credentials, it always errors with: 

```
Spotify connection failed: could not find the Spotify app, it may need to be installed
```

This is due to new changes to package visibility issues on API > 30 https://medium.com/androiddevelopers/package-visibility-in-android-11-cc857f221cd9. Spotify android SDK is already updated to work with this in the latest version https://github.com/spotify/android-sdk/pull/295/files.

So it would be great if we can bump its version here too. Thanks!

### PR DESCRIPTION
**Pull request by hoangvvo**
I updated the submodule to the latest commits.

I also updated the `build.gradle` following the latest setup from https://github.com/callstack/react-native-builder-bob (recommended by RN docs)

Fixed #161

### CODE REVIEW

**Comment by hoangvvo** [comment]
I did a round of testing in my RN app (v0.65.1, android sdk 30) and everything seemed ok.

**Comment by hoangvvo** [comment]
@cjam sorry for pinging but hope this can merged and released whenever you are available since it is currently a blocker for me. Thanks!

**Comment by cjam** [comment]
Awesome thanks for the contribution! I'll try to get this merged and released ASAP

**Comment by hoangvvo** [comment]
@cjam Sorry for pinging but is there any chance for an NPM release? Thanks!

**Comment by hoangvvo** [comment]
> Yes @hoangvvo definitely. I wanted to get it done last week but unfortunately broke my leg at soccer. So I'm hoping to get it done this week. 

Thanks for the confirmation. Hope your leg gets better soon!

**Comment by cjam** [comment]
Ah all good it happens. Glad I did it as a pre-release. Keep me posted.

**Comment by cjam** [comment]
Gotcha. Will look into it soon. Thanks for investigating. 👍

**Comment by hoangvvo** [comment]
The NPM hook that triggers git submodules cmd still causes the external git modules failing to be pulled unfortunately. Only after patching with this PR https://github.com/cjam/react-native-spotify-remote/pull/164 that it can work normally in my case.

**Pull request merged**
